version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: develop
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    commit-message:
      prefix: "deps: "
    labels:
      - "dependencies"
      - "pip"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: develop
    reviewers:
      - turnrdev
    assignees:
      - turnrdev
    commit-message:
      prefix: "chore: "
    labels:
      - "dependencies"
